package shim

import (
	"fmt"
	"os"
	"path/filepath"
)

// shimTemplate is the POSIX sh content written for each shim.
// The shim asks fvm to resolve the real binary at runtime, preserving the
// hybrid shims-first execution model.
const shimTemplate = `#!/bin/sh
# fvm shim: %s
# This file is auto-generated by fvm. Do not edit.
set -e
shim_name="$(basename "$0")"
target="$(fvm which "$shim_name")" || exit $?
exec "$target" "$@"
`

// Generate writes shim scripts to shimDir for each name in names.
// Shims are written with executable permissions and overwrite any existing file.
// shimDir is created if it does not exist.
func Generate(shimDir string, names []string) error {
	if err := os.MkdirAll(shimDir, 0o755); err != nil {
		return fmt.Errorf("shim: create shim dir: %w", err)
	}
	for _, name := range names {
		if err := writeShim(shimDir, name); err != nil {
			return err
		}
	}
	return nil
}

// DefaultNames returns the default set of shim names generated during setup.
func DefaultNames() []string {
	return []string{"foundry", "foundryvtt"}
}

func writeShim(shimDir, name string) error {
	if filepath.Base(name) != name || name == "." || name == ".." {
		return fmt.Errorf("shim: invalid shim name %q", name)
	}
	content := fmt.Sprintf(shimTemplate, name)
	p := filepath.Join(shimDir, name)
	if err := os.WriteFile(p, []byte(content), 0o755); err != nil {
		return fmt.Errorf("shim: write %s: %w", name, err)
	}
	return nil
}
