package config

import (
	"os"

	"github.com/foundry/fvm/internal/paths"
	"gopkg.in/yaml.v3"
)

// Config holds the YAML configuration for fvm stored at ~/.fvm/config.yaml.
type Config struct {
	InstallRoot          string   `yaml:"install_root"`
	ShimNames            []string `yaml:"shim_names"`
	ReleaseChannel       string   `yaml:"release_channel"`
	CacheTTL             string   `yaml:"cache_ttl"`
	AutoRegenerateShims  bool     `yaml:"auto_regenerate_shims"`
	PreferOfficialBuilds bool     `yaml:"prefer_official_builds"`
}

// DefaultShimNames are the shim executables generated by default.
var DefaultShimNames = []string{"foundry"}

// Defaults returns a Config populated with sensible defaults.
func Defaults() Config {
	return Config{
		InstallRoot:          paths.Root(),
		ShimNames:            DefaultShimNames,
		ReleaseChannel:       "stable",
		CacheTTL:             "24h",
		AutoRegenerateShims:  true,
		PreferOfficialBuilds: true,
	}
}

// Load reads a config file from path. If the file does not exist, defaults
// are returned without error. Partial YAML files merge on top of defaults.
func Load(path string) (Config, error) {
	cfg := Defaults()
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return cfg, err
	}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return cfg, err
	}
	return cfg, nil
}

// LoadDefault loads config from the standard ~/.fvm/config.yaml location.
func LoadDefault() (Config, error) {
	return Load(paths.ConfigPath())
}
